use actix_web::web::*;

use crate::handlers::admin_handler;
use crate::middleware;

use super::RateLimiters;

pub fn configure(cfg: &mut ServiceConfig, limiters: RateLimiters) {
    cfg.service(
        scope("/admin")
            .service(
                resource("/pending")
                    .route(get().to(admin_handler::list_pending))
                    .wrap(limiters.read_fair_use.clone())
                    .wrap(limiters.read_circuit_breaker.clone()),
            )
            .service(
                resource("/anonymous-posts/pending")
                    .route(get().to(admin_handler::list_pending_anonymous_posts))
                    .wrap(limiters.read_fair_use.clone())
                    .wrap(limiters.read_circuit_breaker.clone()),
            )
            .service(
                resource("/anonymous-posts/{post_id}/approve")
                    .route(post().to(admin_handler::approve_anonymous_post))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.update_fair_use.clone())
                    .wrap(limiters.update_circuit_breaker.clone()),
            )
            .service(
                resource("/events")
                    .route(
                        get()
                            .to(admin_handler::list_events)
                            .wrap(limiters.read_fair_use.clone())
                            .wrap(limiters.read_circuit_breaker.clone()),
                    )
                    .route(
                        post()
                            .to(admin_handler::create_event)
                            .wrap(middleware::csrf_middleware::CsrfMiddleware)
                            .wrap(limiters.create_fair_use.clone())
                            .wrap(limiters.create_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/events/{event_id}")
                    .route(
                        patch()
                            .to(admin_handler::update_event)
                            .wrap(middleware::csrf_middleware::CsrfMiddleware)
                            .wrap(limiters.update_fair_use.clone())
                            .wrap(limiters.update_circuit_breaker.clone()),
                    )
                    .route(
                        delete()
                            .to(admin_handler::delete_event)
                            .wrap(middleware::csrf_middleware::CsrfMiddleware)
                            .wrap(limiters.delete_fair_use.clone())
                            .wrap(limiters.delete_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/study-topics")
                    .route(
                        get()
                            .to(admin_handler::list_study_topics)
                            .wrap(limiters.read_fair_use.clone())
                            .wrap(limiters.read_circuit_breaker.clone()),
                    )
                    .route(
                        post()
                            .to(admin_handler::create_study_topic)
                            .wrap(middleware::csrf_middleware::CsrfMiddleware)
                            .wrap(limiters.create_fair_use.clone())
                            .wrap(limiters.create_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/study-topics/{topic_id}")
                    .route(
                        patch()
                            .to(admin_handler::update_study_topic)
                            .wrap(middleware::csrf_middleware::CsrfMiddleware)
                            .wrap(limiters.update_fair_use.clone())
                            .wrap(limiters.update_circuit_breaker.clone()),
                    )
                    .route(
                        delete()
                            .to(admin_handler::delete_study_topic)
                            .wrap(middleware::csrf_middleware::CsrfMiddleware)
                            .wrap(limiters.delete_fair_use.clone())
                            .wrap(limiters.delete_circuit_breaker.clone()),
                    ),
            )
            .service(
                resource("/users")
                    .route(get().to(admin_handler::list_users))
                    .wrap(limiters.read_fair_use.clone())
                    .wrap(limiters.read_circuit_breaker.clone()),
            )
            .service(
                resource("/users/{user_id}/approve")
                    .route(post().to(admin_handler::approve_user))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.update_fair_use.clone())
                    .wrap(limiters.update_circuit_breaker.clone()),
            )
            .service(
                resource("/users/{user_id}/role")
                    .route(post().to(admin_handler::set_admin))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.update_fair_use.clone())
                    .wrap(limiters.update_circuit_breaker.clone()),
            )
            .service(
                resource("/users/{user_id}/status")
                    .route(post().to(admin_handler::set_user_status))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.update_fair_use.clone())
                    .wrap(limiters.update_circuit_breaker.clone()),
            )
            .service(
                resource("/users/{user_id}/reset-password")
                    .route(post().to(admin_handler::reset_password))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.update_fair_use.clone())
                    .wrap(limiters.update_circuit_breaker.clone()),
            )
            .service(
                resource("/users/{user_id}")
                    .route(delete().to(admin_handler::delete_user))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.delete_fair_use.clone())
                    .wrap(limiters.delete_circuit_breaker.clone()),
            )
            .service(
                resource("/content/{kind}/{id}")
                    .route(delete().to(admin_handler::delete_content))
                    .wrap(middleware::csrf_middleware::CsrfMiddleware)
                    .wrap(limiters.delete_fair_use.clone())
                    .wrap(limiters.delete_circuit_breaker.clone()),
            ),
    );
}
